const fs=require('fs'),assert=require('node:assert/strict');const {browser,page,load,images,metrics,W}=require('./browser-lib.cjs');const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const b=await browser(),checks=[];try{const p=await page(b);await load(p,'2023-S-lm-q37-37',37);await images(p);await pause(120);
 await p.$eval('#choices',e=>e.scrollIntoView({block:'end'}));await pause(90);await p.screenshot({path:W+'/question-footer-clean.png'});checks.push('old Hangul question lower choices and final crop');
 await load(p,'2022-06-hw-q43-45',45);await images(p);await p.click('#showOriginal');await p.waitForFunction(()=>[...document.querySelectorAll('#inlineOriginal .source-frame')].every(e=>e.dataset.sourceState==='loaded'));await p.$eval('#passageScroll',e=>e.scrollTop=e.scrollHeight);await pause(120);await p.screenshot({path:W+'/check-notice-clean.png'});checks.push('last exam page original inline does not append exam-administration block');
 await load(p,'2026-06-common-q14-17',16);await images(p);await pause(100);const labels=await p.$$eval('.exam-labelled-row .exam-row-label',els=>els.map(e=>e.textContent));assert.deepEqual(labels,['ㄱ.','ㄴ.','ㄷ.','ㄹ.','ㅁ.']);await p.screenshot({path:W+'/list-lines-clean.png'});checks.push('five Korean letter labels separated without changing wording');
 const old=p.imageRequests.length;await p.click('#choices .choice');await pause(100);assert.equal(p.imageRequests.length,old);checks.push('answer clicking does not reload cleaned sources');
 await p.close();const x=await page(b,390,844);await load(x,'2026-06-common-q14-17',16);await images(x);await pause(100);await x.screenshot({path:W+'/list-mobile-clean.png',fullPage:true});assert.deepEqual((await metrics(x)).bad,[]);checks.push('mobile list layout');await x.close();
 fs.writeFileSync(W+'/cleanup-ui-test.json',JSON.stringify({checks},null,2));console.log('PASS',checks.length,checks);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
