const fs=require('fs'),assert=require('node:assert/strict'),puppeteer=require('/Users/shbj/Downloads/mysuneung-cbt-worker/node_modules/puppeteer-core');
const A='/Users/shbj/Downloads/mysuneung-account-worker',W=__dirname,BASE=JSON.parse(fs.readFileSync(A+'/reports/test-server.json')).url;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function login(b,who){const c=await b.createBrowserContext(),p=await c.newPage();p.setDefaultTimeout(15000);await p.setViewport({width:1440,height:1000});await p.goto(BASE+'/my',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.MSNAccount);await p.evaluate(()=>MSNAccount.ready);let r=await p.evaluate(async who=>{const c=await fetch('/api/account/config').then(r=>r.json());return fetch('/api/account/session',{method:'POST',headers:{'Content-Type':'application/json','X-MSN-Login-CSRF':c.login_csrf},body:JSON.stringify({id_token:'test-'+who,over14:true,accept_privacy:true,consent_version:c.consent_version})}).then(r=>r.json())},who);assert.ok(r.user,JSON.stringify(r));await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.MSNAccount);await p.evaluate(()=>MSNAccount.ready);return {c,p}}
(async()=>{const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--ignore-certificate-errors']});const checks=[];try{
 const first=await login(b,'alice'),second=await login(b,'alice'),other=await login(b,'bob');const id='ink-r4-test',uid='2023-S-lm-q37-37';
 const left={tool:'pen',color:'#223344',size:3,points:[{x:.1,y:.2},{x:.2,y:.25}]};const right={...left,surface:'question',question_no:37,anchor:{id:'source-0',x:.05,y:.05,w:.9,h:.85},points:[{x:.2,y:.3},{x:.4,y:.35}]};const eraser={...right,tool:'eraser',points:[{x:.3,y:.31},{x:.33,y:.33}]};
 await first.p.evaluate(async({id,uid,strokes})=>{MSNStorage.setItem('mysuneung-cbt-annotations-'+id,JSON.stringify({[uid]:strokes}));await MSNAccount.sync()}, {id,uid,strokes:[left,right,eraser]});
 await first.p.waitForFunction(()=>MSNAccount.info().pending===0);const firstData=await first.p.evaluate(()=>MSNAccount.list('annotation').map(r=>r.data));assert.equal(firstData.length,1);assert.equal(firstData[0].strokes.length,3);checks.push('existing storage adapter saves left/right/eraser through actual account API');
 await second.p.evaluate(()=>MSNAccount.sync());const restored=await second.p.evaluate(id=>JSON.parse(MSNStorage.getItem('mysuneung-cbt-annotations-'+id)),id);assert.deepEqual(restored[uid],[left,right,eraser]);checks.push('second browser restores question number, anchor and eraser without data loss');
 await other.p.evaluate(()=>MSNAccount.sync());assert.equal(await other.p.evaluate(()=>MSNAccount.list('annotation').length),0);checks.push('separate user cannot see annotation record');
 await second.p.evaluate(()=>document.querySelector('[data-tab="review"]').click());await second.p.waitForSelector('[data-review-filter="drawings"]');await second.p.click('[data-review-filter="drawings"]');await second.p.waitForSelector('[data-view-drawing]');await second.p.click('[data-view-drawing]');
 await second.p.waitForSelector('#drawingSurfaceSelect');let options=await second.p.$$eval('#drawingSurfaceSelect option',els=>els.map(e=>({value:e.value,label:e.textContent})));assert.deepEqual(options.map(o=>o.value),['passage','q37']);checks.push('My Study preview separates passage and question ink');
 await second.p.select('#drawingSurfaceSelect','q37');await pause(100);assert.ok((await second.p.$eval('#drawingSource',e=>e.textContent)).includes('37번 문제'));checks.push('question preview selector and count are correct');await second.p.screenshot({path:W+'/account-question-ink-preview.png'});
 await second.p.select('#drawingSurfaceSelect','passage');assert.ok((await second.p.$eval('#drawingSource',e=>e.textContent)).includes('지문'));checks.push('passage preview remains backward compatible');
 const exported=await first.p.evaluate(()=>MSNAccount.exportData());assert.equal(exported.records[0].data.strokes[1].surface,'question');assert.equal(exported.records[0].data.strokes[1].anchor.id,'source-0');checks.push('account export preserves right-pane annotation metadata');
 fs.writeFileSync(W+'/sync-preview-test.json',JSON.stringify({ok:true,checks},null,2));console.log('PASS',checks.length,checks);
 await first.c.close();await second.c.close();await other.c.close();
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
