import assert from 'node:assert/strict';import fs from 'node:fs';
import {createHandler} from '../reports/worker-check.mjs';import {makeEnv,identity,operation} from './fixtures.mjs';import {challenge} from '../src/bridge.mjs';import {hash,randomToken,sessionCSRF} from '../src/security.mjs';
const env=makeEnv(),h=createHandler({verifyIdentity:async t=>{if(!['alice','bob'].includes(t))throw Error('test only');return identity(t);}}),tests=[];
const test=async(n,f)=>{await f();tests.push(n)};
async function call(route,b,jar,headers={},method){const hs={...(b?{'Content-Type':'application/json',Origin:env.SITE_ORIGIN}:{}),...(jar?{Cookie:jar.cookie,'X-MSN-Account':jar.id,'X-MSN-CSRF':jar.csrf}:{}),...headers};for(const k in hs)if(hs[k]===null)delete hs[k];const r=await h.fetch(new Request(env.SITE_ORIGIN+'/api/account/'+route,{method:method||(b?'POST':'GET'),headers:hs,...(b?{body:JSON.stringify(b)}:{})}),env);return {r,d:await r.json()};}
async function login(name){const c=await call('config'),nonce=c.r.headers.getSetCookie()[0].split(';')[0],s=await call('session',{id_token:name,over14:true,accept_privacy:true,consent_version:c.d.consent_version},null,{Cookie:nonce,'X-MSN-Login-CSRF':c.d.login_csrf});return {cookie:s.r.headers.getSetCookie().find(x=>x.startsWith('__Host-msn-session=')).split(';')[0],id:s.d.user.id,csrf:s.d.csrf};}
const a=await login('alice'),b=await login('bob');
async function link(jar=a){const verifier=randomToken(),state=randomToken(),r=await call('connect/authorize',{client:'universitypredict',state,challenge:await challenge(verifier)},jar);assert.equal(r.r.status,200,JSON.stringify(r.d));const u=new URL(r.d.redirect);assert.equal(u.origin,'https://universitypredict.com');assert.equal(u.pathname,'/account/callback');assert.equal(u.searchParams.get('state'),state);return {code:u.searchParams.get('code'),verifier};}
const exchange=(l,extra={})=>call('connect/exchange',{client:'universitypredict',...l},null,{Origin:null,...extra});
await test('S256 matches known RFC7636 challenge',async()=>assert.equal(await challenge('dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk'),'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM'));
await test('authorization requires signed account and csrf',async()=>{assert.equal((await call('connect/authorize',{client:'universitypredict',state:randomToken(),challenge:randomToken()})).r.status,401);assert.equal((await call('connect/authorize',{client:'universitypredict',state:randomToken(),challenge:randomToken()},a,{'X-MSN-CSRF':'bad'})).r.status,403);});
await test('unknown client cannot choose a redirect',async()=>assert.equal((await call('connect/authorize',{client:'evil',state:randomToken(),challenge:randomToken()},a)).r.status,400));
await test('browser-origin token exchange denied',async()=>{const l=await link();assert.equal((await exchange(l,{Origin:env.SITE_ORIGIN})).r.status,403);});
await test('code alone is insufficient; incorrect verifier cannot consume valid code',async()=>{const l=await link();assert.equal((await exchange({...l,verifier:randomToken()})).r.status,401);assert.equal((await exchange(l)).r.status,200);});
await test('single-use code works once and token maps to authorizing user',async()=>{const l=await link(),r=await exchange(l);assert.equal(r.r.status,200);assert.equal(r.d.account_id,a.id);assert.ok(r.d.session_token);assert.ok(r.r.headers.get('cache-control').includes('no-store'));assert.equal((await exchange(l)).r.status,401);const j={cookie:'__Host-msn-session='+r.d.session_token,id:a.id,csrf:await sessionCSRF(r.d.session_token)};const records=await call('records',undefined,j);assert.equal(records.r.status,200);assert.equal((await call('records',undefined,{...j,id:b.id})).r.status,409);});
await test('expired bridge rejected',async()=>{const l=await link();env.DB.raw.prepare('UPDATE account_bridge_codes SET expires_at=? WHERE code_hash=?').run(Date.now()-1,await hash(l.code));assert.equal((await exchange(l)).r.status,401);});
await test('revoking parent session invalidates outstanding link',async()=>{const parent=await login('alice'),l=await link(parent);await call('logout',{},parent);assert.equal((await exchange(l)).r.status,401);});
await test('favorite and comparison collections are validated and isolated',async()=>{const ops=[operation('university_state','favorites',{items:[{code:'0000001',name:'학교 A'},{code:'0000002',name:'학교 B'}]}),operation('university_state','compare',{items:[{code:'0000002',name:'학교 B'}]})];const r=await call('records/batch',{operations:ops},a);assert.equal(r.r.status,200);assert.equal((await call('records',undefined,b)).d.records.length,0);assert.ok((await call('records',undefined,a)).d.records.find(x=>x.kind==='university_state'&&x.id==='favorites'));});
await test('comparison cap and duplicate university codes enforced',async()=>{for(const items of [[1,2,3,4].map(n=>({code:String(n).padStart(7,'0'),name:'x'})),[{code:'0000001',name:'a'},{code:'0000001',name:'b'}],[{code:'../secret',name:'bad'}]]){assert.equal((await call('records/batch',{operations:[operation('university_state','compare',{items})]},a)).r.status,400);}});
await test('all-session revoke includes linked university browser',async()=>{const l=await link(),r=await exchange(l),j={cookie:'__Host-msn-session='+r.d.session_token,id:a.id,csrf:await sessionCSRF(r.d.session_token)};await call('logout',{all:true},a);assert.equal((await call('records',undefined,j)).r.status,401);});
fs.writeFileSync(new URL('../reports/bridge-tests.json',import.meta.url),JSON.stringify({passed:tests.length,tests},null,2));console.log('BRIDGE_PASS',tests.length);env.DB.raw.close();
