import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {handleMath} from '../src/math-core.mjs';
const require=createRequire(import.meta.url),puppeteer=require('/Users/shbj/Downloads/mysuneung-cbt-worker/node_modules/puppeteer-core');
const repo=path.resolve(new URL('../../..',import.meta.url).pathname),app=path.join(repo,'workers/cbt/app/math.html'),assets=path.join(repo,'workers/accounts/public'),out=path.join(repo,'ops/math-cbt-20260929/evidence');
const errors=[];const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');let response;if(u.pathname.startsWith('/api/cbt/math/')){const chunks=[];for await(const c of req)chunks.push(c);const body=Buffer.concat(chunks);response=await handleMath(new Request('https://mysuneung.com'+u.pathname+u.search,{method:req.method,headers:{'Content-Type':'application/json'},...(req.method==='POST'?{body}: {})}),{});}else if(u.pathname==='/api/account/session')response=Response.json({ok:true,user:null});else if(u.pathname==='/api/visit')response=Response.json({ok:true,today:0,month:0});else if(u.pathname==='/favicon.ico')response=new Response(null,{status:204});else{let file=u.pathname==='/mixed-cbt'?app:path.join(assets,decodeURIComponent(u.pathname));if(!file.startsWith(repo)||!fs.existsSync(file)){res.writeHead(404);res.end('not found');return;}const type=file.endsWith('.js')?'application/javascript':file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.webp')?'image/webp':'text/css';response=new Response(fs.readFileSync(file),{headers:{'Content-Type':type}});}res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch(e){errors.push(String(e));res.writeHead(500);res.end('failed')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
try{const p=await browser.newPage();p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(String(e)));await p.setRequestInterception(true);p.on('request',async r=>{const u=new URL(r.url());if(u.origin===base){r.continue();return;}if(u.hostname==='mysuneung.com'&&u.pathname.startsWith('/account-assets/')){const f=path.join(assets,u.pathname);if(fs.existsSync(f)){await r.respond({status:200,contentType:f.endsWith('.webp')?'image/webp':'application/javascript',body:fs.readFileSync(f)});return;}}r.abort();});
 await p.setViewport({width:1440,height:1000});await p.goto(base+'/mixed-cbt?subject=math',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.CBTLearningUI&&document.querySelectorAll('#years .year').length===14&&document.querySelectorAll('input[name="sourceFamily"]').length===3);
 assert.match(await p.$eval('.math-coverage',e=>e.textContent),/4,960문항/);assert.match(await p.$eval('.math-coverage',e=>e.textContent),/2,600문항/);
 await p.click('label[for="math-source-edu"]');await p.waitForFunction(()=>document.querySelector('#sourceHint').textContent.includes('교육청 고3 전국연합'));
 assert.equal(await p.$eval('#generate',e=>e.textContent),'교육청 30문항 만들기');
 await p.click('#generate');await p.waitForFunction(()=>window.flat?.length===30&&!document.querySelector('#app').classList.contains('hidden'));
 const full=await p.evaluate(()=>({source_family:exam.source_family,score:exam.max_score,n:flat.length,sources:flat.map(x=>x.set.source.exam_family),months:[...new Set(flat.map(x=>x.set.source.month))],years:[...new Set(flat.map(x=>x.set.source.academic_year))]}));
 assert.equal(full.source_family,'education_office');assert.equal(full.n,30);assert.equal(full.score,100);assert.ok(full.sources.every(x=>x==='education_office'));assert.ok(full.years.every(y=>y>=2022));
 await p.screenshot({path:path.join(out,'math-edu-full-1440.png')});
 // 2021 legacy ga/na era: return to start, enable education-office and keep one intact 30-question paper.
 await p.evaluate(()=>{MSNStorage.removeItem('mysuneung-math-cbt-current');location.reload()});await p.waitForFunction(()=>window.CBTLearningUI&&document.querySelectorAll('input[name="sourceFamily"]').length===3&&!document.querySelector('#start').classList.contains('hidden'));
 await p.evaluate(()=>{selectedYears=new Set([2015]);selectedCategories.clear();refreshYearModeUi();document.querySelector('input[name="choice"][value="A"]').checked=true;refreshYearModeUi();initCategories();});
 await p.waitForFunction(()=>document.querySelector('#math-source-edu')&&!document.querySelector('#math-source-edu').disabled&&document.querySelector('input[name="choice"]:checked')?.value==='A');
 await p.click('label[for="math-source-edu"]');await p.waitForFunction(()=>document.querySelector('#generate').textContent==='교육청 30문항 만들기');
 await p.click('#generate');await p.waitForFunction(()=>window.flat?.length===30&&!document.querySelector('#app').classList.contains('hidden'));
 const legacy=await p.evaluate(()=>({source_family:exam.source_family,choice:exam.choice,score:exam.max_score,n:flat.length,years:[...new Set(flat.map(x=>x.set.source.academic_year))],families:[...new Set(flat.map(x=>x.set.source.exam_family))],sessions:[...new Set(flat.map(x=>x.q.question_key.slice(0,7)))]}));
 assert.equal(legacy.source_family,'education_office');assert.equal(legacy.choice,'A');assert.equal(legacy.n,30);assert.equal(legacy.score,100);assert.deepEqual(legacy.years,[2015]);assert.deepEqual(legacy.families,['education_office']);assert.equal(legacy.sessions.length,1);
 await p.evaluate(()=>{MSNStorage.removeItem('mysuneung-math-cbt-current');location.reload()});await p.waitForFunction(()=>document.querySelectorAll('input[name="sourceFamily"]').length===3&&document.querySelectorAll('#categoryGroups .cat').length>0);
 await p.evaluate(()=>{selectedYears=new Set([2022,2023,2024,2025,2026,2027]);selectedCategories.clear();refreshYearModeUi();initCategories();});await p.waitForFunction(()=>document.querySelector('input[name="choice"]:checked')?.value==='prob');
 await p.click('#modeCustom');await p.click('label[for="math-source-edu"]');await p.waitForFunction(()=>document.querySelectorAll('#categoryGroups .cat').length>0);
 const cats=await p.$$eval('#categoryGroups .cat',els=>els.map(e=>({name:e.dataset.category,text:e.textContent})));assert.ok(cats.length>5);assert.ok(cats.every(x=>/\d+문항/.test(x.text)));
 assert.ok(fs.readFileSync(app,'utf8').includes('모두 정답'));assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'math-edu-ui.json'),JSON.stringify({passed:14,full,legacy,category_count:cats.length,errors},null,2));console.log('MATH_EDU_UI_PASS 14');
}catch(e){console.error(e);console.log('PAGE_ERRORS',errors);process.exitCode=1;}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
